# Generated by Django 3.2.4 on 2021-06-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210528_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False},
        ),
    ]
